version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: nir
      MONGO_INITDB_ROOT_PASSWORD: nir
    volumes:
      - db:/data/db
    ports:
      - "27017:27017"

volumes:
  db: